# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20171228_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
