# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20171228_0958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quota',
            new_name='ConfigSMS',
        ),
    ]
