# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20171228_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='sender',
        ),
        migrations.AddField(
            model_name='configsms',
            name='account_sid',
            field=models.CharField(default='AC8acd164ef4c16be2293b2d2fde61b02c', max_length=50),
        ),
        migrations.AddField(
            model_name='configsms',
            name='account_token',
            field=models.CharField(default='d6cf89d37b05fd9b8ffec3f56b5cd202', max_length=50),
        ),
        migrations.AddField(
            model_name='configsms',
            name='default_number',
            field=models.CharField(default='+56964590279', max_length=20),
        ),
        migrations.AddField(
            model_name='sms',
            name='config',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sms.ConfigSMS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sms',
            name='number_from',
            field=models.CharField(max_length=15),
        ),
    ]
