# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-29 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20171228_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='error_code',
            field=models.IntegerField(blank=True, choices=[(1, 'Error en datos de reemplazos'), (2, 'Error en valores de reemplazos'), (3, 'Error en valores de reemplazos y datos'), (4, 'Error servicio de envió de sms')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='error_detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='configsms',
            name='account_token',
            field=models.CharField(default='f8b6dc4bc9b7c39e7a673cc37384ac35', max_length=50),
        ),
        migrations.AlterField(
            model_name='sms',
            name='body',
            field=models.TextField(max_length=1600),
        ),
    ]
